// autogenerated by sql-generate v0.3.0 on Tue May 06 2014 15:17:55 GMT-0400 (EDT)

var sql = require('sql');


/**
 * SQL definition for public.migrations
 */
exports.migrations = sql.define({
	name: 'migrations',
	columns: [
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'run_on' }
	]
});


/**
 * SQL definition for public.users
 */
exports.users = sql.define({
	name: 'users',
	columns: [
		{ name: 'id' },
		{ name: 'email' },
		{ name: 'refresh_token' },
		{ name: 'google_id' }
	]
});


