// autogenerated by sql-generate v0.3.0 on Fri May 09 2014 15:05:56 GMT-0400 (EDT)

var sql = require('sql');


/**
 * SQL definition for public.assignment_template
 */
exports.assignment_template = sql.define({
	name: 'assignment_template',
	columns: [
		{ name: 'id' },
		{ name: 'link' }
	]
});


/**
 * SQL definition for public.courses
 */
exports.courses = sql.define({
	name: 'courses',
	columns: [
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'owner_id' }
	]
});


/**
 * SQL definition for public.migrations
 */
exports.migrations = sql.define({
	name: 'migrations',
	columns: [
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'run_on' }
	]
});


/**
 * SQL definition for public.sessions
 */
exports.sessions = sql.define({
	name: 'sessions',
	columns: [
		{ name: 'id' },
		{ name: 'user_id' },
		{ name: 'refresh_token' },
		{ name: 'auth_token' },
		{ name: 'expiry' }
	]
});


/**
 * SQL definition for public.teacher_infos
 */
exports.teacher_infos = sql.define({
	name: 'teacher_infos',
	columns: [
		{ name: 'id' },
		{ name: 'user_id' },
		{ name: 'name' },
		{ name: 'school' },
		{ name: 'about' },
		{ name: 'pending' },
		{ name: 'applied_at' },
		{ name: 'alternate_email' }
	]
});


/**
 * SQL definition for public.teachers
 */
exports.teachers = sql.define({
	name: 'teachers',
	columns: [
		{ name: 'id' },
		{ name: 'user_id' },
		{ name: 'teacher_info_id' }
	]
});


/**
 * SQL definition for public.users
 */
exports.users = sql.define({
	name: 'users',
	columns: [
		{ name: 'id' },
		{ name: 'email' },
		{ name: 'refresh_token' },
		{ name: 'google_id' }
	]
});


