// autogenerated by sql-generate v0.3.0 on Thu May 08 2014 13:40:27 GMT-0400 (EDT)

var sql = require('sql');


/**
 * SQL definition for public.migrations
 */
exports.migrations = sql.define({
	name: 'migrations',
	columns: [
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'run_on' }
	]
});


/**
 * SQL definition for public.sessions
 */
exports.sessions = sql.define({
	name: 'sessions',
	columns: [
		{ name: 'id' },
		{ name: 'user_id' },
		{ name: 'refresh_token' },
		{ name: 'auth_token' },
		{ name: 'expiry' }
	]
});


/**
 * SQL definition for public.users
 */
exports.users = sql.define({
	name: 'users',
	columns: [
		{ name: 'id' },
		{ name: 'email' },
		{ name: 'refresh_token' },
		{ name: 'google_id' }
	]
});


